# Generated by Django 4.2.14 on 2024-07-22 19:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('theblog', '0006_alter_post_body'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='snippet',
            field=models.CharField(default='Check out blog', max_length=255),
        ),
    ]
